# TODO: (Upgrade Rust and) use https://github.com/rust-lang/rfcs/blob/master/text/2282-profile-dependencies.md
#       cf. https://github.com/rust-lang/rust/issues/48683
#       Keep debugging symbols in our release code (but not in the dependencies),
#       in order for our panics to show up in iOS debugger and crash reports.

[package]
name = "mm2"
version = "0.1.0"
edition = "2018"

# Waiting for https://doc.rust-lang.org/beta/cargo/reference/unstable.html#default-run to become stable.
# cf. https://github.com/rust-lang/cargo/issues/2200 (closed, should work after a Rust upgrade).
#default-run = "mm2"

[features]
native = [
  "common/native", "peers/native", "coins/native", "portfolio/native",
  "hyper", "tokio-core"
]

[[bin]]
name = "mm2"
path = "mm2src/mm2_bin.rs"

[lib]
name = "mm2"
path = "mm2src/mm2_lib.rs"
crate-type = ["staticlib"]
test = false
doctest = false
bench = false

[profile.dev]
# Enable light optimizations. We want a debuggable version but not a completely dumb one.
# Can override this with "set CARGO_BUILD_RUSTFLAGS=-C opt-level=0".
opt-level = 1

[profile.test]
# Should probably match "profile.dev", given that we're reusing the libraries.
opt-level = 1

[dependencies]
bigdecimal = { version = "0.1.0", features = ["serde"] }
bitcrypto = { git = "https://github.com/artemii235/parity-bitcoin.git" }
coins = { path = "mm2src/coins" }
common = { path = "mm2src/common" }
crc = "1.8"
crossbeam = "0.6"
dirs = "1"
enum-primitive-derive = "0.1"
fomat-macros = "0.2"
futures = "0.1"
futures-cpupool = "0.1"
# NB: tokio-timer 2+ is targeted at "Tokio runtime" and heavy load (spawns several timer threads there),
# whereas futures-timer works with any reactor and spawns one global timer thread (fits out load better).
futures-timer = "0.1"
gstuff = "0.5"
hashbrown = {version = "0.1.8", features = ["serde", "nightly"]}
hex = "0.3.2"
http = "0.1"
hyper = { version = "0.12", optional = true }
keys = { git = "https://github.com/artemii235/parity-bitcoin.git" }
lazy_static = "1.3"
libc = "0.2"
num-traits = "0.2"
rpc = { git = "https://github.com/artemii235/parity-bitcoin.git" }
peers = { path = "mm2src/peers" }
portfolio = { path = "mm2src/portfolio" }
primitives = { git = "https://github.com/artemii235/parity-bitcoin.git" }
rand = "0.6"
regex = "1"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
serialization = { git = "https://github.com/artemii235/parity-bitcoin.git" }
serialization_derive = { git = "https://github.com/artemii235/parity-bitcoin.git" }
tokio-core = { version = "0.1", optional = true }
unwrap = "1.2"
uuid = { version = "0.7", features = ["serde", "v4"] }
winapi = "0.3"

[workspace]
members = [
  "mm2src/coins"
]
